# Generated by Django 6.0.3 on 2026-04-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
