# Generated by Django 6.0.3 on 2026-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_usernotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='currentStreak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='longestStreak',
            field=models.IntegerField(default=0),
        ),
    ]
