# Generated by Django 6.0.3 on 2026-03-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notified_1d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notified_1h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notified_5h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notified_5m',
            field=models.BooleanField(default=False),
        ),
    ]
