# Generated by Django 6.0.3 on 2026-03-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
