# Generated by Django 6.0.3 on 2026-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customuser_alter_emailotp_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_completed_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
