# Generated by Django 6.0.3 on 2026-04-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customuser_has_completed_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
